### ISSUE TITLE
l2d_dems dsm no output 

### ISSUE THREAD

**Issue by lledoux** [Applied-GeoSolutions/lidar2dems#37]
I am running the following command:
 ```l2d_dems dsm lasclass/ -s density_r056_classes.shp --maxsd 2.5 --maxangle 20 --maxz 150 -v ```

and am receiving an warning related to the return number of points in my data

```
Pipeline file: /tmp/tmpAl5OMI.xml
(readers.las Warning: 1): /projects/ForestDisturbance/data/Lidar/ArgenTech/lasclass/density_r056_classes-0_l2d_s1c3.las: Found invalid value of '6' for point's return number.
(readers.las Warning: 1): /projects/ForestDisturbance/data/Lidar/ArgenTech/lasclass/density_r056_classes-0_l2d_s1c3.las: Found invalid value of '6' for point's number of returns.
 ```

The process runs through the entire  ```lasclass /```    directory, but no output is created

**Comment by ircwaves** [comment]
Per our discussion, see if you can drop excessive returns points with `pdal translate --writers.las.discard_high_return_numbers=true`

**Comment by ircwaves** [comment]
Any word on if this made it such that you were able to create the DSM?

**Comment by lledoux** [comment]
Oh yeah, sorry.  I meant to update this thread- I had to re-run the classifications before creating the DSM, and it takes around 100 hours to run the classification.  So... I'll know in about two more days.

**Comment by lledoux** [comment]
So after re-running the classifications, I attempted to call ```l2d_dems dsm lasclass/ -s density_r056_classes.shp --outdir dems --maxsd 2.5 --maxz 130 --maxangle 20 --gapfill -v ``` and received this error:
 ```Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/l2d/scripts/dems.py", line 106, in main
    pouts = create_dems(lasfiles, args.demtype, site=feature, gapfill=args.gapfill, **kwargs)
  File "build/bdist.linux-x86_64/egg/l2d/pdal.py", line 322, in create_dems
    radius=rad, site=site, outdir=outdir, suffix=suffix, overwrite=overwrite, **kwargs))
  File "build/bdist.linux-x86_64/egg/l2d/pdal.py", line 393, in create_dem
    raise Exception("Error creating dems: %s" % ' '.join(fouts))
Exception: Error creating dems: max den 
```

* and no output is created

**Comment by lledoux** [comment]
I needed to reclassify the .las file (as the data had been delivered to us already classified), using values that lidar2dems would use in the creation of the DSM and DTM.  I thought that this would have been done in the l2d_classify step, but maybe I'm missing something.  Instead, I re-classified using LAStools, and then proceeded to create a DSM and DTM.
